-- Config blocks allow you to configure, document, and test your data assets.
config {
  type: "table", // Creates a table in BigQuery.
  description: "The description of the table",
  columns: {
    number: "Description of the first column", // Column descriptions are pushed to BigQuery.
  }
}

-- The rest of a SQLX file contains your SELECT statement used to create the table.

SELECT 1 as test